services:
  documentserver:
    image: onlyoffice/documentserver:latest
    container_name: onlyoffice_docs
    restart: always
    ports:
      - "8080:80"
    environment:
      - JWT_ENABLED=false
      - ALLOW_PRIVATE_IP_ADDRESS=true
      - ALLOW_META_IP_ADDRESS=true
    volumes:
      - onlyoffice_logs:/var/log/onlyoffice
      - onlyoffice_data:/var/www/onlyoffice/Data
      - onlyoffice_lib:/var/lib/onlyoffice
      - onlyoffice_db:/var/lib/postgresql

volumes:
  onlyoffice_logs:
  onlyoffice_data:
  onlyoffice_lib:
  onlyoffice_db: